<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <?=$this->headTitle()?>

    <style>
        <!--
        select {font-size:12px;}
        A:link {text-decoration: none; color: blue}
        A:visited {text-decoration: none; color: purple}
        A:active {text-decoration: red}
        A:hover {text-decoration: underline; color:red}
        -->
    </style>
    <style type="text/css">
        <!--
        .ft0{font-style:normal;font-weight:normal;font-size:9px;font-family:Times New Roman;color:#000000;}
        .ft1{font-style:normal;font-weight:bold;font-size:9px;font-family:Times New Roman;color:#000000;}
        .ft2{font-style:normal;font-weight:normal;font-size:10px;font-family:Times New Roman;color:#000000;}
        .ft3{font-style:normal;font-weight:bold;font-size:13px;font-family:Times New Roman;color:#000000;}
        .ft4{font-style:normal;font-weight:normal;font-size:8px;font-family:Times New Roman;color:#000000;}
        -->
    </style>
</head>
<body vlink="#FFFFFF" link="#FFFFFF" bgcolor="#ffffff">
<div style="position:absolute;top:0;left:0"><img width="827" height="1169" src="<?=$this->baseUrl()?>/img/pg_0001.jpg" ALT=""></div>
<div style="position:absolute;top:48;left:256"><span class="ft0">Унифиц ированная форма № КО</span></div>
<div style="position:absolute;top:48;left:409"><span class="ft0">-</span></div>
<div style="position:absolute;top:48;left:413"><span class="ft0">1</span></div>
<div style="position:absolute;top:48;left:418"><span class="ft0"> </span></div>
<div style="position:absolute;top:48;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:532;left:514"><span class="ft0">  </span></div>
<div style="position:absolute;top:48;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:48;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:61;left:256"><span class="ft0">Утверждена постановлением Госкомстата</span></div>
<div style="position:absolute;top:61;left:456"><span class="ft0">  </span></div>
<div style="position:absolute;top:61;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:61;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:61;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:73;left:256"><span class="ft0">России от 18.08.98 № 88</span></div>
<div style="position:absolute;top:74;left:372"><span class="ft0"> </span></div>
<div style="position:absolute;top:74;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:74;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:73;left:619"><span class="ft0"> ООО «ФинРусь»</span></div>
<div style="position:absolute;top:74;left:700"><span class="ft0"> </span></div>
<div style="position:absolute;top:88;left:41"><span class="ft1"> </span></div>
<div style="position:absolute;top:88;left:475"><span class="ft1">  </span></div>
<div style="position:absolute;top:88;left:524"><span class="ft1">  </span></div>
<div style="position:absolute;top:87;left:634"><span class="ft1"> (организация)</span></div>
<div style="position:absolute;top:88;left:685"><span class="ft1">  </span></div>
<div style="position:absolute;top:98;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:97;left:414"><span class="ft0"> Код</span></div>
<div style="position:absolute;top:98;left:433"><span class="ft0"> </span></div>
<div style="position:absolute;top:98;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:98;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:98;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:115;left:284"><span class="ft0">Форма по ОКУД</span></div>
<div style="position:absolute;top:116;left:364"><span class="ft0"> </span></div>
<div style="position:absolute;top:116;left:404"><span class="ft0"> 0310001</span></div>
<div style="position:absolute;top:116;left:443"><span class="ft0"> </span></div>
<div style="position:absolute;top:116;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:116;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:113;left:613"><span class="ft2"> КВИТАНЦИЯ</span></div>
<div style="position:absolute;top:113;left:706"><span class="ft2">  </span></div>
<div style="position:absolute;top:130;left:132"><span class="ft0">ООО «ФинРусь»</span></div>
<div style="position:absolute;top:131;left:213"><span class="ft0">  </span></div>
<div style="position:absolute;top:130;left:318"><span class="ft0"> по ОКПО</span></div>
<div style="position:absolute;top:131;left:364"><span class="ft0"> </span></div>
<div style="position:absolute;top:131;left:423"><span class="ft0">  </span></div>
<div style="position:absolute;top:131;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:131;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:131;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:145;left:147"><span class="ft1">(организация)</span></div>
<div style="position:absolute;top:146;left:197"><span class="ft1"> </span></div>
<div style="position:absolute;top:146;left:307"><span class="ft1">  </span></div>
<div style="position:absolute;top:151;left:423"><span class="ft0">  </span></div>
<div style="position:absolute;top:146;left:475"><span class="ft1">  </span></div>
<div style="position:absolute;top:146;left:524"><span class="ft1">  </span></div>
<div style="position:absolute;top:146;left:534"><span class="ft1">  </span></div>
<div style="position:absolute;top:157;left:207"><span class="ft0"> </span></div>
<div style="position:absolute;top:157;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:157;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:157;left:533"><span class="ft0"> к приходному кассовому ордеру №</span></div>
<div style="position:absolute;top:157;left:701"><span class="ft0"> </span></div>
<div style="position:absolute;top:157;left:748"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:154"><span class="ft1">(структурное подразделение)</span></div>
<div style="position:absolute;top:172;left:259"><span class="ft1">  </span></div>
<div style="position:absolute;top:172;left:376"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:171;left:533"><span class="ft0"> от “</span></div>
<div style="position:absolute;top:172;left:552"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:573"><span class="ft0">  </span></div>
<div style="position:absolute;top:171;left:592"><span class="ft0"> &quot;</span></div>
<div style="position:absolute;top:172;left:598"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:653"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:698"><span class="ft0">  </span></div>
<div style="position:absolute;top:172;left:719"><span class="ft0">  </span></div>
<div style="position:absolute;top:171;left:742"><span class="ft0"> г.</span></div>
<div style="position:absolute;top:172;left:750"><span class="ft0"> </span></div>
<div style="position:absolute;top:185;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:185;left:343"><span class="ft0"> Номер </span></div>
<div style="position:absolute;top:198;left:334"><span class="ft0">документа</span></div>
<div style="position:absolute;top:218;left:354"><span class="ft0"><?=$this->payment['id']?></span></div>
<div style="position:absolute;top:198;left:384"><span class="ft0"> </span></div>
<div style="position:absolute;top:185;left:422"><span class="ft0"> Дата </span></div>
<div style="position:absolute;top:198;left:404"><span class="ft0">составления</span></div>
<div style="position:absolute;top:218;left:396"><span class="ft0"><?=date('Y-m-d', strtotime($this->payment['date']))?></span></div>
<div style="position:absolute;top:198;left:462"><span class="ft0"> </span></div>
<div style="position:absolute;top:185;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:185;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:185;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:199;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:199;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:199;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:198;left:533"><span class="ft0"> Принято от</span></div>
<div style="position:absolute;top:198;left:633"><span class="ft0"> <?=$this->client['last_name'] . ' ' . $this->client['first_name'] . ' ' . $this->client['middle_name']?></span></div>
<div style="position:absolute;top:199;left:588"><span class="ft0"> </span></div>
<div style="position:absolute;top:199;left:694"><span class="ft0">  </span></div>
<div style="position:absolute;top:214;left:81"><span class="ft2">ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР</span></div>
<div style="position:absolute;top:215;left:315"><span class="ft2"> </span></div>
<div style="position:absolute;top:215;left:359"><span class="ft2">  </span></div>
<div style="position:absolute;top:215;left:433"><span class="ft2">  </span></div>
<div style="position:absolute;top:217;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:217;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:217;left:660"><span class="ft0">  </span></div>
<div style="position:absolute;top:232;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:232;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:232;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:231;left:533"><span class="ft0"> Основание:</span></div>
<div style="position:absolute;top:232;left:588"><span class="ft0"> </span></div>
<div style="position:absolute;top:232;left:689"><span class="ft0">  </span></div>
<div style="position:absolute;top:245;left:44"><span class="ft0">Де</span></div>
<div style="position:absolute;top:245;left:57"><span class="ft0">бет</span></div>
<div style="position:absolute;top:245;left:73"><span class="ft0">  </span></div>
<div style="position:absolute;top:245;left:174"><span class="ft0"> Кре</span></div>
<div style="position:absolute;top:245;left:192"><span class="ft0">дит</span></div>
<div style="position:absolute;top:245;left:209"><span class="ft0"> </span></div>
<div style="position:absolute;top:245;left:317"><span class="ft0"> Сумма, </span></div>
<div style="position:absolute;top:258;left:313"><span class="ft0">руб. коп.</span></div>
<div style="position:absolute;top:320;left:317"><span class="ft0"><?=$this->payment['amount']?></span></div>
<div style="position:absolute;top:258;left:356"><span class="ft0"> </span></div>
<div style="position:absolute;top:245;left:390"><span class="ft0"> Код</span></div>
<div style="position:absolute;top:245;left:409"><span class="ft0"> </span></div>
<div style="position:absolute;top:258;left:378"><span class="ft0">це</span></div>
<div style="position:absolute;top:258;left:389"><span class="ft0">ле</span></div>
<div style="position:absolute;top:258;left:400"><span class="ft0">во</span></div>
<div style="position:absolute;top:258;left:410"><span class="ft0">го</span></div>
<div style="position:absolute;top:258;left:421"><span class="ft0"> </span></div>
<div style="position:absolute;top:270;left:373"><span class="ft0">наз</span></div>
<div style="position:absolute;top:270;left:388"><span class="ft0">н</span></div>
<div style="position:absolute;top:270;left:394"><span class="ft0">а</span></div>
<div style="position:absolute;top:270;left:399"><span class="ft0">че</span></div>
<div style="position:absolute;top:270;left:409"><span class="ft0">ния</span></div>
<div style="position:absolute;top:271;left:427"><span class="ft0"> </span></div>
<div style="position:absolute;top:245;left:454"><span class="ft0">  </span></div>
<div style="position:absolute;top:245;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:245;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:245;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:259;left:94"><span class="ft0"> </span></div>
<div style="position:absolute;top:258;left:113"><span class="ft0"> код</span></div>
<div style="position:absolute;top:259;left:130"><span class="ft0"> </span></div>
<div style="position:absolute;top:258;left:132"><span class="ft0">струк</span></div>
<div style="position:absolute;top:259;left:159"><span class="ft0">-</span></div>
<div style="position:absolute;top:271;left:119"><span class="ft0">тур</span></div>
<div style="position:absolute;top:271;left:135"><span class="ft0">но</span></div>
<div style="position:absolute;top:271;left:146"><span class="ft0">го</span></div>
<div style="position:absolute;top:271;left:157"><span class="ft0"> </span></div>
<div style="position:absolute;top:284;left:114"><span class="ft0">под</span></div>
<div style="position:absolute;top:284;left:131"><span class="ft0">раз</span></div>
<div style="position:absolute;top:284;left:146"><span class="ft0">де</span></div>
<div style="position:absolute;top:284;left:157"><span class="ft0">-</span></div>
<div style="position:absolute;top:297;left:124"><span class="ft0">ле</span></div>
<div style="position:absolute;top:297;left:134"><span class="ft0">ния</span></div>
<div style="position:absolute;top:297;left:152"><span class="ft0"> </span></div>
<div style="position:absolute;top:258;left:170"><span class="ft0"> кор</span></div>
<div style="position:absolute;top:258;left:186"><span class="ft0">рес</span></div>
<div style="position:absolute;top:258;left:202"><span class="ft0">пон</span></div>
<div style="position:absolute;top:259;left:220"><span class="ft0"> -</span></div>
<div style="position:absolute;top:271;left:171"><span class="ft0">ди</span></div>
<div style="position:absolute;top:271;left:182"><span class="ft0">рую</span></div>
<div style="position:absolute;top:271;left:202"><span class="ft0">щий </span></div>
<div style="position:absolute;top:284;left:185"><span class="ft0">счет,</span></div>
<div style="position:absolute;top:284;left:209"><span class="ft0">  </span></div>
<div style="position:absolute;top:297;left:178"><span class="ft0">суб</span></div>
<div style="position:absolute;top:297;left:194"><span class="ft0">счет</span></div>
<div style="position:absolute;top:297;left:215"><span class="ft0"> </span></div>
<div style="position:absolute;top:258;left:235"><span class="ft0"> код ана</span></div>
<div style="position:absolute;top:258;left:270"><span class="ft0">ли</span></div>
<div style="position:absolute;top:258;left:281"><span class="ft0">ти</span></div>
<div style="position:absolute;top:259;left:293"><span class="ft0"> -</span></div>
<div style="position:absolute;top:271;left:233"><span class="ft0">чес</span></div>
<div style="position:absolute;top:271;left:248"><span class="ft0">ко</span></div>
<div style="position:absolute;top:271;left:259"><span class="ft0">го уче</span></div>
<div style="position:absolute;top:271;left:288"><span class="ft0">та</span></div>
<div style="position:absolute;top:271;left:298"><span class="ft0"> </span></div>
<div style="position:absolute;top:259;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:259;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:259;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:272;left:475"><span class="ft0"> </span></div>
<div style="position:absolute;top:272;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:272;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:286;left:475"><span class="ft0"> </span></div>
<div style="position:absolute;top:286;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:286;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:299;left:475"><span class="ft0"> </span></div>
<div style="position:absolute;top:299;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:299;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:59"><span class="ft0"> </span></div>
<div style="position:absolute;top:318;left:94"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:138"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:197"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:266"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:335"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:400"><span class="ft0">  </span></div>
<div style="position:absolute;top:318;left:454"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:533"><span class="ft0"> Сумма</span></div>
<div style="position:absolute;top:322;left:603"><span class="ft0"><?=intval($this->payment['amount'])?></span></div>
<div style="position:absolute;top:322;left:566"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:615"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:664"><span class="ft0"> руб.</span></div>
<div style="position:absolute;top:322;left:684"><span class="ft0"> </span></div>
<div style="position:absolute;top:322;left:709"><span class="ft0">  </span></div>
<div style="position:absolute;top:322;left:734"><span class="ft0"> коп.</span></div>
<div style="position:absolute;top:322;left:704"><span class="ft2"> <?=strpos($this->payment['amount'], '.') === false ? '00' : str_pad(substr($this->payment['amount'], strpos($this->payment['amount'], '.') + 1), 2, '0', STR_PAD_LEFT)?> </span></div>
<div style="position:absolute;top:322;left:754"><span class="ft0"> </span></div>
<div style="position:absolute;top:337;left:41"><span class="ft1"> </span></div>
<div style="position:absolute;top:337;left:475"><span class="ft1">  </span></div>
<div style="position:absolute;top:337;left:524"><span class="ft1">  </span></div>
<div style="position:absolute;top:337;left:534"><span class="ft1">  </span></div>
<div style="position:absolute;top:337;left:596"><span class="ft1"> (цифрами)</span></div>
<div style="position:absolute;top:337;left:634"><span class="ft1"> </span></div>
<div style="position:absolute;top:337;left:662"><span class="ft1">  </span></div>
<div style="position:absolute;top:346;left:41"><span class="ft0">Принято от</span></div>
<div style="position:absolute;top:346;left:141"><span class="ft0"> <?=$this->client['last_name'] . ' ' . $this->client['first_name'] . ' ' . $this->client['middle_name']?></span></div>
<div style="position:absolute;top:346;left:96"><span class="ft0">  </span></div>
<div style="position:absolute;top:346;left:291"><span class="ft0">  </span></div>
<div style="position:absolute;top:346;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:346;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:346;left:660"><span class="ft0">  </span></div>
<div style="position:absolute;top:360;left:41"><span class="ft1"> </span></div>
<div style="position:absolute;top:360;left:475"><span class="ft1">  </span></div>
<div style="position:absolute;top:360;left:524"><span class="ft1">  </span></div>
<div style="position:absolute;top:345;left:569"><span class="ft2"> <?=Finrus_Utils::num2str($this->payment['amount'])?> </span></div>
<div style="position:absolute;top:360;left:639"><span class="ft1"> (</span></div>
<div style="position:absolute;top:360;left:642"><span class="ft1">прописью)</span></div>
<div style="position:absolute;top:360;left:680"><span class="ft1"> </span></div>
<div style="position:absolute;top:369;left:41"><span class="ft0">Основание:</span></div>
<div style="position:absolute;top:370;left:96"><span class="ft0"> </span></div>
<div style="position:absolute;top:370;left:291"><span class="ft0">  </span></div>
<div style="position:absolute;top:370;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:370;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:370;left:662"><span class="ft0">  </span></div>
<div style="position:absolute;top:383;left:256"><span class="ft0"> </span></div>
<div style="position:absolute;top:383;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:383;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:383;left:591"><span class="ft0">  </span></div>
<div style="position:absolute;top:383;left:654"><span class="ft0"> руб.</span></div>
<div style="position:absolute;top:383;left:674"><span class="ft0"> </span></div>
<div style="position:absolute;top:383;left:698"><span class="ft0">  </span></div>
<div style="position:absolute;top:383;left:722"><span class="ft0"> коп.</span></div>
<div style="position:absolute;top:383;left:742"><span class="ft0"> </span></div>
<div style="position:absolute;top:396;left:41"><span class="ft0">Сумма</span></div>
<div style="position:absolute;top:396;left:141"><span class="ft2"> <?=Finrus_Utils::num2str($this->payment['amount'])?> </span></div>
<div style="position:absolute;top:396;left:73"><span class="ft0"> </span></div>
<div style="position:absolute;top:396;left:91"><span class="ft0">  </span></div>
<div style="position:absolute;top:396;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:396;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:396;left:533"><span class="ft0"> В том числе</span></div>
<div style="position:absolute;top:396;left:591"><span class="ft0"> </span></div>
<div style="position:absolute;top:396;left:694"><span class="ft0">  </span></div>
<div style="position:absolute;top:410;left:41"><span class="ft1"> </span></div>
<div style="position:absolute;top:410;left:260"><span class="ft1"> (прописью)</span></div>
<div style="position:absolute;top:410;left:301"><span class="ft1"> </span></div>
<div style="position:absolute;top:410;left:475"><span class="ft1">  </span></div>
<div style="position:absolute;top:410;left:524"><span class="ft1">  </span></div>
<div style="position:absolute;top:410;left:534"><span class="ft1">  </span></div>
<div style="position:absolute;top:420;left:202"><span class="ft0"> </span></div>
<div style="position:absolute;top:419;left:369"><span class="ft0"> руб.</span></div>
<div style="position:absolute;top:420;left:389"><span class="ft0">  </span></div>
<div style="position:absolute;top:420;left:413"><span class="ft0">  </span></div>
<div style="position:absolute;top:419;left:439"><span class="ft0"> коп.</span></div>
<div style="position:absolute;top:420;left:459"><span class="ft0"> </span></div>
<div style="position:absolute;top:420;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:420;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:419;left:533"><span class="ft0"> “</span></div>
<div style="position:absolute;top:420;left:539"><span class="ft0">  </span></div>
<div style="position:absolute;top:420;left:556"><span class="ft0">  </span></div>
<div style="position:absolute;top:419;left:573"><span class="ft0"> &quot;</span></div>
<div style="position:absolute;top:420;left:578"><span class="ft0"> </span></div>
<div style="position:absolute;top:420;left:635"><span class="ft0">  </span></div>
<div style="position:absolute;top:420;left:681"><span class="ft0">  </span></div>
<div style="position:absolute;top:420;left:702"><span class="ft0">  </span></div>
<div style="position:absolute;top:419;left:724"><span class="ft0"> г.</span></div>
<div style="position:absolute;top:420;left:732"><span class="ft0"> </span></div>
<div style="position:absolute;top:432;left:41"><span class="ft0">В том числе</span></div>
<div style="position:absolute;top:433;left:99"><span class="ft0">  </span></div>
<div style="position:absolute;top:433;left:291"><span class="ft0">  </span></div>
<div style="position:absolute;top:433;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:433;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:433;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:446;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:446;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:446;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:452;left:571"><span class="ft0"> М.П. (штампа)</span></div>
<div style="position:absolute;top:453;left:641"><span class="ft0"> </span></div>
<div style="position:absolute;top:459;left:41"><span class="ft0">Приложение</span></div>
<div style="position:absolute;top:459;left:101"><span class="ft0"> </span></div>
<div style="position:absolute;top:459;left:291"><span class="ft0">  </span></div>
<div style="position:absolute;top:459;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:459;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:473;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:473;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:473;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:473;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:41"><span class="ft0">Главный бухгалтер</span></div>
<div style="position:absolute;top:485;left:133"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:187"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:228"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:316"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:388"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:533"><span class="ft0"> Главный бухгалтер</span></div>
<div style="position:absolute;top:485;left:625"><span class="ft0"> </span></div>
<div style="position:absolute;top:485;left:659"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:685"><span class="ft0">  </span></div>
<div style="position:absolute;top:485;left:739"><span class="ft0">  </span></div>
<div style="position:absolute;top:499;left:94"><span class="ft1"> </span></div>
<div style="position:absolute;top:499;left:169"><span class="ft1"> (подпись)</span></div>
<div style="position:absolute;top:499;left:205"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:236"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:273"><span class="ft1"> (расшифровка подписи)</span></div>
<div style="position:absolute;top:499;left:359"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:429"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:478"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:527"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:583"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:641"><span class="ft1"> (подпись)</span></div>
<div style="position:absolute;top:499;left:676"><span class="ft1"> </span></div>
<div style="position:absolute;top:499;left:686"><span class="ft1">  </span></div>
<div style="position:absolute;top:499;left:695"><span class="ft1"> (расшифровка подписи)</span></div>
<div style="position:absolute;top:499;left:781"><span class="ft1"> </span></div>
<div style="position:absolute;top:508;left:41"><span class="ft0">Получил кассир</span></div>
<div style="position:absolute;top:509;left:118"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:169"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:215"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:295"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:366"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:508;left:533"><span class="ft0"> Кассир</span></div>
<div style="position:absolute;top:509;left:567"><span class="ft0"> </span></div>
<div style="position:absolute;top:509;left:608"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:636"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:688"><span class="ft0">  </span></div>
<div style="position:absolute;top:509;left:739"><span class="ft0">  </span></div>
<div style="position:absolute;top:523;left:83"><span class="ft1"> </span></div>
<div style="position:absolute;top:522;left:151"><span class="ft1"> (подпись)</span></div>
<div style="position:absolute;top:523;left:187"><span class="ft1">  </span></div>
<div style="position:absolute;top:523;left:220"><span class="ft1">  </span></div>
<div style="position:absolute;top:522;left:252"><span class="ft1"> (расшифровка подписи)</span></div>
<div style="position:absolute;top:523;left:338"><span class="ft1"> </span></div>
<div style="position:absolute;top:523;left:418"><span class="ft1">  </span></div>
<div style="position:absolute;top:523;left:478"><span class="ft1">  </span></div>
<div style="position:absolute;top:523;left:527"><span class="ft1">  </span></div>
<div style="position:absolute;top:523;left:556"><span class="ft1">  </span></div>
<div style="position:absolute;top:522;left:590"><span class="ft1"> (подпись)</span></div>
<div style="position:absolute;top:523;left:625"><span class="ft1"> </span></div>
<div style="position:absolute;top:523;left:637"><span class="ft1">  </span></div>
<div style="position:absolute;top:522;left:645"><span class="ft1"> (расшифровка подписи)</span></div>
<div style="position:absolute;top:523;left:731"><span class="ft1"> </span></div>
<div style="position:absolute;top:523;left:762"><span class="ft1">  </span></div>
<div style="position:absolute;top:532;left:41"><span class="ft0"> </span></div>
<div style="position:absolute;top:532;left:475"><span class="ft0">  </span></div>
<div style="position:absolute;top:532;left:524"><span class="ft0">  </span></div>
<div style="position:absolute;top:532;left:534"><span class="ft0">  </span></div>
<div style="position:absolute;top:544;left:39"><span class="ft0"> </span></div>
<div style="position:absolute;top:557;left:39"><span class="ft0"> </span></div>
</body>
</html>