<div class="center">
<a href="<?=$this->url(array('controller' => 'client', 'action' => 'add'), 'default')?>" class="default-button">Добавить клиента</a>
<a href="<?=$this->url(array('controller' => 'credit', 'action' => 'add'), 'default')?>" class="default-button">Зарегистрировать кредит</a>
<a href="<?=$this->url(array('controller' => 'payment', 'action' => 'add'), 'default')?>" class="default-button">Провести платеж</a>
</div>