<?=$this->searchForm?>

<table class="default-table ui-state-default">
    <thead>
        <tr>
            <th class="ui-widget-header">#</th>
            <th class="ui-widget-header sortable" field="last_name">Клиент</th>
            <th class="ui-widget-header sortable" field="amount">Сумма</th>
            <!--
            <th class="ui-widget-header">Остаток</th>
            <th class="ui-widget-header">Last Payment</th>
            <th class="ui-widget-header">Next Payment</th>
            -->
            <th class="ui-widget-header sortable" field="opening_date">Открытие</th>
            <th class="ui-widget-header">Закрытие</th>
            <th class="ui-widget-header">Статус</th>
            <th class="ui-widget-header">Действия</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="8" class="ui-widget-content">
                <?=$this->paginationControl($this->data,
                    'Sliding',
                    'paging.phtml');
                ?>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <? if (!empty($this->data)): ?>
            <? foreach($this->data as $k => $value): ?>
                <tr class="ui-widget <?=($k % 2 == 0) ? 'ui-state-default' : 'ui-state-hover'?>">
                    <td class="ui-widget-content"><?=$value['id']?></td>
                    <td class="ui-widget-content"><a class="client-link" href="<?=$this->url(array('controller' => 'client', 'action' => 'info', 'id' => $value['client_id']), 'default', true)?>"><?=$value['last_name']?> <?=$value['first_name']?></a></td>
                    <td class="ui-widget-content"><?=$value['amount']?></td>
                    <!--
                    <td class="ui-widget-content"><?=$value['remain']?></td>
                    <td class="ui-widget-content"><?=$value['last_payment_date']?></td>
                    <td class="ui-widget-content"><?=$value['next_payment_date']?></td>
                    -->
                    <td class="ui-widget-content"><?=$value['opening_date']?></td>
                    <td class="ui-widget-content"><?=$value['closing_date']?></td>
                    <td class="ui-widget-content">
                        <? if ($value['status'] == 'active'): ?>
                            Активен
                        <? elseif ($value['status'] == 'failed'): ?>
                            Просрочен
                        <? elseif ($value['status'] == 'successfull'): ?>
                            Погашен
                        <? endif; ?>
                    </td>
                    <td class="ui-widget-content">
                        Скачать <a href="<?=$this->url(array('controller' => 'credit', 'action' => 'agreement', 'id' => $value['id']), 'default', true)?>">Договор</a>
                        <a href="<?=$this->url(array('controller' => 'credit', 'action' => 'print', 'id' => $value['id']), 'default', true)?>">Чек</a>
                    </td>
                </tr>
            <? endforeach; ?>
        <? else: ?>
            <tr class="ui-widget odd">
                <td colspan="8" class="ui-widget-content"> нет данных. </td>
            </tr>
        <? endif; ?>
    </tbody>
</table>

<?=$this->render('buttons.phtml')?>