<?=$this->searchForm?>

<table class="default-table ui-state-default">
    <thead>
        <tr>
            <th class="ui-widget-header">#</th>
            <th class="ui-widget-header sortable" field="first_name">Логин</th>
            <th class="ui-widget-header sortable" field="last_name">Роль</th>
            <th class="ui-widget-header sortable" field="middle_name">Филиал</th>
            <th class="ui-widget-header sortable" field="created_date">Зарегистрирован</th>
            <th class="ui-widget-header">Действия</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="6" class="ui-widget-content">
                <?=$this->paginationControl($this->data,
                    'Sliding',
                    'paging.phtml');
                ?>
            </td>
        </tr>
    </tfoot>
    <tbody>
        <? if (!empty($this->data)): ?>
            <? foreach($this->data as $k => $value): ?>
                <tr class="ui-widget <?=($k % 2 == 0) ? 'ui-state-default' : 'ui-state-hover'?>">
                    <td class="ui-widget-content"><?=$value['id']?></td>
                    <td class="ui-widget-content"><?=$value['login']?></td>
                    <td class="ui-widget-content"><?=$value['type'] == 'admin' ? 'Администратор' : 'Оператор'?></td>
                    <td class="ui-widget-content"><?=$value['name']?></td>
                    <td class="ui-widget-content"><?=$value['created_date']?></td>
                    <td>
                        <? if (!empty($value['active'])): ?>
                            <a href="<?=$this->url(array('controller' => 'user', 'action' => 'status', 'disable' => 1, 'id' => $value['id']), 'default', true)?>">Отключить</a>
                        <? else: ?>
                            <a href="<?=$this->url(array('controller' => 'user', 'action' => 'status', 'disable' => 0, 'id' => $value['id']), 'default', true)?>">Включить</a>
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
        <? else: ?>
            <tr class="ui-widget odd">
                <td colspan="6" class="ui-widget-content"> no data. </td>
            </tr>
        <? endif; ?>
    </tbody>
</table>

<div class="center" style="padding: 15px 0;">
    <a href="<?=$this->url(array('controller' => 'user', 'action' => 'add'), 'default')?>" class="default-button">Создать</a>
</div>

<?=$this->render('buttons.phtml')?>